[build]
  base = "CascadeProjects/ai-roleplay-creator-demo"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  # Only OPENAI_API_KEY is required for deployment

[[plugins]]
  package = "@netlify/plugin-nextjs"
