[build]
  command = "npm install react-markdown remark-gfm && npm install && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  # Only OPENAI_API_KEY is required for deployment
  # Increase timeout from default 10s to 26s (max for regular Netlify accounts)
  AWS_LAMBDA_FUNCTION_TIMEOUT = "26"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Increase function timeout to handle longer-running operations
[functions]
  node_bundler = "esbuild"
  # Increase timeout from default 10s to 26s (max for regular Netlify accounts)
  included_files = ["**/*"]

# Function timeout is set in the build.environment section above

# Add debugging for Next.js
[dev]
  framework = "#static"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public"
  autoLaunch = true
